# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPage',
            new_name='HomePage',
        ),
    ]
