# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191127_1627'),
        ('home', '0003_auto_20191202_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bid_id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user_id',
        ),
        migrations.AddField(
            model_name='page',
            name='product_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
