# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200106_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='product_id',
            new_name='product',
        ),
    ]
