# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200106_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
