# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20191127_1627'),
        ('home', '0006_auto_20200106_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='product',
        ),
        migrations.AddField(
            model_name='page',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='page',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
