# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
