# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20191217_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_no',
            field=models.IntegerField(default=1),
        ),
    ]
