# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
