# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
