# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20191127_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 27, 17, 56, 1, 772733), null=True),
        ),
    ]
