# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20191127_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, default=datetime.timezone, null=True),
        ),
    ]
