# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20191127_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, default='timezone', null=True),
        ),
    ]
