# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='artefact',
            field=models.CharField(choices=[('HISTO', 'Historical'), ('CULTU', 'Cultural'), ('RELIG', 'Religious'), ('MEDIA', 'Media')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
